<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <?php

        foreach ($posts as $post) {
            ?>
            <div class="post-preview">
                <h2 class="post-title">
            <?php
                echo $post['title'];
            ?>
                </h2>
                <p>
            <?php
                echo nl2br($post['content']);
            ?>
                </p>
            </div>
            <hr>
            <?php
        }
        ?>
    </div>
</div>
